

// thesse are the libraries that will be used to import all the functions we need
use std::{cmp::Ordering, io};

use rand::Rng;

fn main() {
    println!("The best guessing game .....!");
    loop {
    println!("Enter your guess ");
    let mut guess :String = String::new();
    
    io::stdin()
        .read_line(&mut guess)
        .expect("Failed to input guess");
    let guess:u32 = match guess.trim().parse() {
        Ok(num) => num,
        Err(_) => continue, // err code added to help keep the program running even though the user enters a char
    }; // rust uses shadowing to enable that i can use the sae variable tye and just reassign it to a new datatype

    println!("You guessed {guess}");


    print!("Generating a second number \n");
    let sec_num = rand::thread_rng().gen_range(1..=100); // to generate a number between 1 and 100
    println!("The random number is {sec_num} \n");

    
        // conditional that will compare the number we predicted with the number generated by the system
        match guess.cmp(&sec_num) {
        Ordering::Less => println!("Too small"),
        Ordering::Greater => println!("Too large"),
        Ordering::Equal => {
            println!("Wow you got it wonderful");
            break;
        }   
    }
    }
 
}
